### ISSUE TITLE
Dependency quarkus-narayana-jta does not seem to be optional

### ISSUE THREAD

**Issue by turing85** [quarkiverse/quarkus-pooled-jms#44]
## Describe the bug
When using `quarkus-artemis-jms` in conjunction with `quarkus-pooled-jms` and without xa-supprt, e.g. through the following `application.yml`:

```
quarkus:
  artemis:
    url: tcp://${ARTEMIS_HOST:localhost}:${ARTEMIS_PORT:61616}
    username: ${ARTEMIS_USERNAME:artemis}
    password: ${ARTEMIS_PASSWORD:artemis}
  pooled-jms:
    pooling:
      enabled: true
    max-connections: 2
```

then `quarkus-pooled-jms` fails on `mvn package` with:
```
...
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.13.3.Final:build (default) on project sender: Failed to build quarkus application: Failed to load steps from class io.quarkiverse.messaginghub.pooled.jms.deployment.PooledJmsProcessor: io/quarkus/narayana/jta/runtime/TransactionManagerConfiguration: io.quarkus.narayana.jta.runtime.TransactionManagerConfiguration -> [Help 1]
...
```

## Expected behaviour
Application compiles, and `ConnectionFactory` is not XA-capable.

## Actual behaviour
Compilation fails.

## Technica details
`quarkus` version: `2.13.3.FINAL`, `2.14.0.FINAL`
`quarkus-artemis-jms` version: `1.3.0`, `2.0.0`, `2.0.1` (have not verified others)
`quakrus-pooled-jms`version: `1.0.3` (have not verified others)
`javac` version: `17.0.4`

## Reproducer
- checkout https://github.com/turing85/quarkus-camel-jms, branch `bug-report`
- package module `sender`: `mvn -pl sender clean package`
- observe the compilation error

## Additional Information
If we uncomment [`sender/pom.xml`, Lines 35 to 38](https://github.com/turing85/quarkus-camel-jms/blob/bug-report/sender/pom.xml#L35-L38), the application compiles as expected.
